# Blog info
blog_name: Jvaeyhcd
slogan: You're uinique, nothing can replace you.
url: http://www.Jvaeyhcd.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: iOS, Android, App开发, 前端开发

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/Jvaeyhcd
    target_blank: true
  - name: Coding
    url: https://coding.net/u/Jvaeyhcd
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: search what you want

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 chedahuang@icloud.com

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，打赏Jvaeyhcd
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
# blog_name_font_familiy: calligraffittiregular
blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 29df66b98641fa1eb4edb792fef116c9

# Comment service
disqus_shortname: jvaeyhcd
# duoshuo_shortname: jvaeyhcd


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "喜欢数学，擅长编程，苹果脑残粉."
    - "App前端开发工程师，擅长iOS、Android开发，最近在学习RxJava，RxSwift，ReactiveCocoa、React Native等一系列技术"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@Jvaeyhcd"
    text_value_url: https://github.com/Jvaeyhcd
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@Jvaeyhcd"
    text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "chedahuang@icloud.com"
  - type: location
    icon: icon-location
    text_value: Chengdu

link:
  - name: 方米团队
    info: 技术从积累开始
    url: https://funmi.github.io
    avatar: https://avatars1.githubusercontent.com/u/6712603?v=3&s=200
  - name: Che Rong
    info: 如果耐不住寂寞，你就看不到繁华
    url: https://crdym.github.io
    avatar: https://www.bugclose.com/oss/res/head/head12.jpg
  - name: EyreFree
    info: It’s hard to have ideas and easy to give up.
    url: http://www.eyrefree.org/
    avatar: https://dn-coding-net-production-static.qbox.me/3f0503a5-2696-44e1-98dd-d755a07c6c2d.jpg?imageMogr2/auto-orient/format/jpeg/crop/!549x549a0a0
  - name: callmewhy
    info: 如果耐不住寂寞，你就看不到繁华
    url: http://blog.callmewhy.com
    avatar: https://avatars1.githubusercontent.com/u/6276527?v=3&s=460
  - name: gaoryrt
    info: Blog Name Goes Here
    url: http://gaoryrt.com
    avatar: https://avatars0.githubusercontent.com/u/5306513?v=3&s=460

project:
  - type: personal
    name: HcdCachePlayer
    url: https://github.com/Jvaeyhcd/HcdCachePlayer
    intro: A video player with cache
  - type: personal
    name: HcdGuideView
    url: https://github.com/Jvaeyhcd/HcdGuideView
    intro: An easy way to add a guide page in your app
  - type: personal
    name: HcdActionSheet
    url: https://github.com/Jvaeyhcd/HcdActionSheet
    intro: A custom ActionSheet
  - type: personal
    name: HcdPopMenu
    url: https://github.com/Jvaeyhcd/HcdPopMenu
    intro: 一个类似新浪微博的PopMenu
  - type: personal
    name: Cut-Polygon
    url: https://github.com/Jvaeyhcd/Cut-Polygon
    intro: 我的毕业设计一个多边形分割小游戏
  - type: company
    name: 步步到
    url: https://appsto.re/cn/PJzjab.i
    intro: 全民快递 同城配送
